### ISSUE TITLE
Deleting a rigorous distillation column crashes DWSim

### ISSUE THREAD

**Issue by alchemyst** [DanWBR/dwsim5#4] opened 2018-04-27 12:33 UTC
It is not possible to delete a rigorous distillation column from the worksheet without the application crashing.

Minimal steps to replicate:

1. Start DWsim
2. Cancel startup wizard
3. Drag rigorous distillation column onto flowsheet
4. Right click
5. Delete
6. Select "Yes"

Application crashes.

DWsim version 5.2r1 on MacOS 10.13.4 using Mono 5.10.1

**Comment by DanWBR** [comment] 2018-05-01 19:50
I couldn't reproduce this bug. Can you do it again and attach the "lasterror.txt" file from your Documents/DWSIM Application Data folder?

**Comment by alchemyst** [comment] 2018-05-02 05:25
Thank you for your attention @DanWBR. I followed the same steps and got a crash again. I attach both the file you asked for and contents of the macOS error report window:

* [lasterror.txt](https://github.com/DanWBR/dwsim5/files/1965990/lasterror.txt)
* [macos_errorwindow.txt](https://github.com/DanWBR/dwsim5/files/1965991/macos_errorwindow.txt)

**Comment by DanWBR** [comment] 2018-05-02 14:54
Fixed in https://github.com/DanWBR/dwsim5/commit/eb54540b3eee80c6bcbb58a553819a59e3993668#diff-05fea94ea4d0c151bfb55349523f8997

While the update isn't out, you can enable the 'View/Open Object Editor after Selection' in the Global Settings Panel:

![](https://snag.gy/JjIPKh.jpg)

**Closed as completed** 2018-05-11 12:27 UTC
